### ISSUE TITLE
span and word breaks

### ISSUE THREAD

**Issue by dauwhe** [w3c/dpub-accessibility#12]
The section on drop caps implies that AT sees spans as word breaks. I've been discussing this with some members of the CSSWG, and they were very surprised by this behavior. Why does AT do this? Span has no intrinsic meaning, and visual renderers do not supply space around spans.

**Comment by deborahgu** [comment]
We're taking it out of the note because the only gap is browser outreach (drop cap support). But we want CSSWG to understand that screen readers treat spans as navigable, individual objects because they're so often used that way. Our screen reader users assure us this is a necessary feature, given how spans are used.
