### ISSUE TITLE
duplicate unclear paragraph

### ISSUE THREAD

**Issue by mattgarrish** [w3c/dpub-accessibility#14]
Section 2.9 on semantic list heads has this paragraph before and after the example:

It is tempting to use HTML5 h1 – h6 elements but these elements may contain the ARIA role="heading" attribute, offering unwanted default navigation. A potentially useful option would be to include a role value as part of an element called "listtitle" (or something similar). The option to include a semantic title in a list requires support in visual as well as aural presentations.

What does the first sentence mean, though? The "heading" role is the implied semantic for h1-h6.

Also, what does "requies support in visual ... presentations" mean? Is it something beyond CSS?

**Comment by clapierre** [comment]
From Matt Garrish
I'm still concerned about the first sentence, as it suggests that role="heading" on h1-h6 affects navigation. In practice, you shouldn't put role="heading" on those elements; the role is implied and AT make navigation to them available.

I wasn't sure if the sentence was supposed to reference the idea of using the role on other elements, but as it is the sentence could be shortened to:

It is tempting to use HTML h1-h6 elements, but these elements offer unwanted default navigation.

Otherwise, to cover both case you could say something like:

It is tempting to use HTML h1-h6 elements, or add role="heading" to a non-heading element, but in both cases the result is unwanted default navigation.

**Comment by clapierre** [comment]
From Matt Garrish
 noticed this sentence in section 2.7:

Additionally, the EPUB 3.1 revision working group agreed to deprecate the speech properties due to lack of adoption.

This isn't technically true. EPUB 3.1 has removed the -epub- prefixed versions of the speech properties, along with others we defined. The primary reason is that these prefixes aren't compatible with the web and require an additional layer of support, but it's also been the case that having them hasn't hastened adoption any.

EPUB 3 still supports CSS 3 Speech as much as any of the browser cores reading systems are built on do (i.e., not at all). The properties are neither endorsed nor discouraged.
