### ISSUE TITLE
incorrect characterisation of css speech in epub

### ISSUE THREAD

**Issue by mattgarrish** [w3c/dpub-accessibility#18]
I noticed this sentence in section 2.7:

> Additionally, the EPUB 3.1 revision working group agreed to deprecate the speech properties due to lack of adoption.

This isn't technically true. EPUB 3.1 has removed the -epub- prefixed versions of the speech properties, along with others we defined. The primary reason is that these prefixes aren't compatible with the web and require an additional layer of support, but it's also been the case that having them hasn't hastened adoption any.

EPUB 3 still supports CSS 3 Speech as much as any of the browser cores reading systems are built on do (i.e., not at all). The properties are neither endorsed nor discouraged.

**Comment by mattgarrish** [comment]
And to the sentence before:

> The CSS3 Speech module [CSS3-SPEECH] doesn't currently address pronunciation. 

I would say nor should it. CSS is the wrong place to be handling text pronunciation. Why should a user agent have to render all the CSS styles in order to determine what to send to the underlying speech engine. That's what's holding it back from even simpler voicing support.

What I was suggesting in the other issue I opened was to strip this and mention SSML instead, which is a technology for addressing phonetic pronunciation but is currently not available. Perhaps remove the last two sentences and add a new paragraph like:

The Speech Synthesis Markup Language (SSML) is another option for phonetic pronunciations, but it is currently not supported in HTML. EPUB attempted to address this shortcoming through the introduction of SSML attributes, but the attributes are unique to that format, limited to XHTML and not well supported within it. A solution that similarly simplifies SSML but brings support to all HTML user agents is needed.

**Comment by clapierre** [comment]
From Matt Garrish
I noticed this sentence in section 2.7:

Additionally, the EPUB 3.1 revision working group agreed to deprecate the speech properties due to lack of adoption.

This isn't technically true. EPUB 3.1 has removed the -epub- prefixed versions of the speech properties, along with others we defined. The primary reason is that these prefixes aren't compatible with the web and require an additional layer of support, but it's also been the case that having them hasn't hastened adoption any.

EPUB 3 still supports CSS 3 Speech as much as any of the browser cores reading systems are built on do (i.e., not at all). The properties are neither endorsed nor discouraged.
