### ISSUE TITLE
Annotation (A2)

### ISSUE THREAD

**Issue by iherman** [w3c/dpub-accessibility#30]
The appendix makes a reference to the Annotation WG, and says 

"User created annotations and highlights adding personal notes to a document must be accessible for creation, editing, and access. The W3C Annotations WG is aware of the accessibility requirement."

I am not sure this remark is really justified, in the sense that the A. WG is defining a general model and protocol but, at this point, the issue is not specifically addressed. With the charter of that WG ending in autumn this year, I do not think it will.

I would suggest to change this section on that the TF will stay in contact with the Anno WG and its descendants (ie, either a CG that will take over maintenance, or a newly chartered WG if that is indeed what will happen) to work on this issue.

**Comment by lrosenthol** [comment]
How about:

Annotations are a general web requirement, but they are a vital need in the digital publishing industry. 
These annotations (incl. highlights & adding personal notes to a document) must be accessible for creation, editing, and access. The W3C Annotations WG is aware of the requirements of accessibility both in UAs as well as the format.

Because of the importance of annotations in the industry, the DPub Accessibility TF will continue to stay in communication with the W3C Annotation WG and its descendants to address the open issues in this area.
